name: release quayio latest
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  python-best-pratices:
    uses: droposhado/workflows/.github/workflows/python-best-practices.yml@main
    with:
      python_version: "3.10"

  build-push:
    needs: python-best-pratices
    uses: droposhado/workflows/.github/workflows/docker-build-push.yml@main
    with:
      registry: quay.io
      repo: droposhado/sabedoria
      tag: latest
      push: true
    secrets:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
